bash

gcloud compute instances create

meu-servidor \

--machine-type=n1-standard-8 \

--memory=8GB \

-image-project-ubuntu-os-cloud \ \

- -image-family-ubuntu-2004-1ts

-zone=southamerica-east1-a \

--accelerator=nvidia-tesla-t4 \

-boot-disk-size=500GB \

--boot-disk-type=pd-ssd \

--network-interface-network=default

--metadata-from-file=startup-scrip t=script.sh
